version: "3"

services:
  test:
    container_name: test
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./app:/home/node/app    

  
  
